module.exports ={

    COUNTER_INCREMENT: 'COUNTER INCREMENT',
    COUNTER_DICREMENT: 'COUNTER DICREMENT',
    RESET_COUNTER:'RESET COUNTER',
    
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT'


}

